- name: ensure there is a /etc/marathon directory
  file: path=/etc/marathon state=directory
  notify: restart marathon

- name: ensure there is a /var/log/marathon directory
  file: path=/var/log/marathon state=directory
  notify: restart marathon

- name: ensure marathon.conf file is in place
  template: src=marathon.j2 dest=/etc/marathon/marathon.conf
  notify: restart marathon

- name: ensure marathon is running
  service: name=marathon state=running
