---

#
# Stop
#

- hosts: mesos_masters
  tasks:
    - service: name=marathon state=stopped

- hosts: mesos_masters
  tasks:
    - service: name=mesos-master state=stopped
    - command: /bin/sleep 2

- hosts: mesos_masters
  tasks:
    - service: name=zookeeper state=stopped
    - command: /bin/sleep 2

- hosts: mesos_slaves
  tasks:
    - service: name=mesos-slave state=stopped
    - command: /bin/sleep 2

#
# Start
#

- hosts: mesos_masters
  serial: True
  tasks:
    - service: name=zookeeper state=running
    - command: /bin/sleep 10

- hosts: mesos_masters
  serial: True
  tasks:
    - service: name=mesos-master state=running
    - command: /bin/sleep 10

- hosts: mesos_masters
  serial: True
  tasks:
    - service: name=marathon state=running
    - command: /bin/sleep 10

- hosts: mesos_slaves
  serial: True
  tasks:
    # FIXME: Shouldn't have to be stopping zookeeper
    - service: name=zookeeper state=stopped enabled=no
    - service: name=mesos-slave state=restarted
