- name: install proxy file for apt
  template: src=01proxy.j2 dest=/etc/apt/apt.conf.d/01proxy

# FIXME: use module
- name: install mesosphere repository key
  #shell: apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: setup mesosphere repository
  template: src=mesosphere.j2 dest=/etc/apt/sources.list.d/mesosphere.list

- name: install required packages
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - zookeeperd
    - default-jre
    - python-setuptools
    - python-protobuf
    - curl
    - mesos
    - marathon
